print("this is activity 2")
print("gonna keep writing lines of code")
print("hopefully this works")
print("I'm saving a new version with every line of code i type")
print("should be goood after this one")
print("wait whoops I didn't copy it to onedrive")
print("kinda funny that I forgot cause that's like the only thing I'm supposed to do")
print("gonna drop a couple more print statements")
print("too lazy to do anything fancy")
print("nope i still did it wrong")
print("now it looks right")
print("this will be the last one")
print("just kidding this is the last one")
